Repository Rans7777/panel, pull requests merged in 2025-03, with the labels that each got.

#15 laravel 12へアップデート
  .github/workflows/laravel.yml
  composer.json
  composer.lock
Labels: dependencies

#58 注文確定ボタンの修正
  app/Filament/Pages/OrderPage.php
Labels: bug

#65 ログレベルの色を修正
  app/Filament/Pages/ActivityLogs.php
Labels: bug

#64 0円でもプラス表記を修正
  app/Filament/Widgets/SalesOverview.php
Labels: bug

#66 ソートの追加
  app/Filament/Resources/OrderResource.php
  app/Filament/Resources/ProductResource.php
  app/Filament/Resources/UserResource.php
  database/migrations/2025_03_12_110528_add_sort_product.php
  database/migrations/2025_03_12_110924_add_sort_order.php
  database/migrations/2025_03_12_111046_add_sort_user.php
Labels: enhancement

#68 画像の最適化の再追加
  app/Filament/Resources/ProductResource.php
  composer.json
  composer.lock
Labels: enhancement

#69 ログインページの改善
  app/Filament/Pages/Auth/Login.php
  composer.json
  composer.lock
  config/services.php
  resources/views/filament/pages/auth/login.blade.php
  tests/Feature/LoginTest.php
Labels: enhancement

#63 注文ページをfilamentからvue.jsに移行
  .github/workflows/build.yml
  app/Filament/Pages/OrderPage.php
  app/Http/Controllers/API/OrderController.php
  app/Http/Controllers/API/ProductController.php
  bootstrap/app.php
  composer.json
  composer.lock
  config/sanctum.php
  database/migrations/2025_03_12_065321_create_personal_access_tokens_table.php
  package-lock.json
  package.json
  resources/js/app.js
  resources/js/components/OrderPage.vue
  resources/views/filament/pages/order-page.blade.php
  resources/views/order.blade.php
  routes/api.php
  routes/web.php
  tests/Feature/Http/Controllers/API/OrderControllerTest.php
  tests/Feature/Http/Controllers/API/ProductControllerTest.php
  tests/Feature/OrderPageTest.php
  tests/Unit/OrderCalculationTest.php
  vite.config.js
Labels: enhancement

#95 ページの改善
  app/Filament/Pages/OrderHistory.php
  app/Filament/Pages/OrderPage.php
  app/Filament/Resources/OrderHistoryResource.php
  app/Filament/Resources/ProductResource.php
  app/Filament/Widgets/SalesOverview.php
  database/migrations/2025_01_30_112222_create_products_table.php
  database/migrations/2025_01_30_113826_create_orders_table.php
  database/migrations/2025_03_14_101019_add_allergens_to_products_table.php
  database/migrations/2025_03_14_140140_add_uuid_orders_column.php
  resources/js/components/MenuPage.vue
  resources/js/components/OrderHistory.vue
  resources/js/components/OrderPage.vue
  resources/views/menu.blade.php
  resources/views/order-history.blade.php
  resources/views/order.blade.php
Labels: enhancement
